config/routes.rb
Rails.application.routes.draw do
  resources :profiles

  match '/auth/:provider/callback', :to => 'sessions#create', :via => [:get, :post]
  match 'auth/failure', :to => 'sessions#failure', :via => [:get, :post]

  get 'sessions/clear'
  get 'session/debug'
  match 'sessions/destroy', :as => 'logout', :via => [:get, :post]
	resources :users, only: [:destroy] do
    resources :profiles, only: [:show, :edit, :update, :destroy]
  end

	resources :timetables do

	end
	get 'timesheets/landing', :as => :timesheets_landing
  root 'timesheets#landing'

  match 'timetables/admin', :as => 'timetables_admin', :via => [:get, :post]
  match 'timetables/admin/:id', :as => 'timetables_user', :to => 'timetables#user', :via => [:get, :post]
  match 'timetables/admin/:id/new', :as => 'user_new_timetable', :to => 'timetables#user_new', :via => [:get, :post]
  match 'timetables/admin/:id/:table_id', :as => 'timetables_user_edit', :to => 'timetables#user_edit', :via => [:get, :post]
  delete 'timetables/admin/:id/:table_id', :to => 'timetables#user_destroy'
  match 'timetables/admin_archive', :as => 'timetables_admin_archive', :via => [:get, :post]

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
    @admin_user = admins.to_s.include? current_user.email.to_s
  end

  # POST /profiles
  def create
    @profile = Profile.new(profile_params)

    if @profile.save
      redirect_to @profile, notice: 'Profile was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /profiles/1
  def update
    if @profile.update(profile_params)
      redirect_to @profile, notice: 'Profile was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /profiles/1
  def destroy
    @profile.destroy
    redirect_to profiles_url, notice: 'Profile was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def profile_params
      params.require(:profile).permit(:privilege, :org, :org2, :grad, :manager_id, :user_id, :machine_1, :machine_2)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.haml
= form_for @profile do |f|
  - if @profile.errors.any?
    #error_explanation
      %h2= "#{pluralize(@profile.errors.count, "error")} prohibited this profile from being saved:"
      %ul
        - @profile.errors.full_messages.each do |message|
          %li= message
  - if (@profile.org == nil and @profile.org2 == nil) or @admin_user
    .field
      = f.label "Organization"
      = f.select(:org, Organization.all.collect{|org| [org.num + " " + org.name, org.num]}, {prompt: 'Select an organization'})
    .field
      = f.label "Organization 2"
      = f.select(:org2, Organization.all.collect{|org| [org.num + " " + org.name, org.num]}, {prompt: 'Select an organization'})
  .field
    = f.label "Main Machine"
    = f.text_field :machine_1
  .field
    = f.label "Alternate Machine"
    = f.text_field :machine_2
  .field
    = f.label "Graduate Student"
    = f.check_box :grad
  .actions
    .row_without_padding
      = f.submit 'Save', :class=> 'btn bg-dark text-light white'
      = link_to 'Back to Dashboard', timetables_path, class: 'btn btn-light bg-dark text-light white'

app/views/profiles/edit.html.haml
%h1 Editing profile

= render 'form'

app/views/profiles/index.html.haml
%h1 Listing profiles

%table
  %thead
    %tr
      %th Privilege
      %th Org
      %th Org2
      %th Grad
      %th Manager
      %th User
      %th
      %th
      %th

  %tbody
    - @profiles.each do |profile|
      %tr
        %td= profile.privilege
        %td= profile.org
        %td= profile.org2
        %td= profile.grad
        %td= profile.manager_id
        %td= profile.user
        %td= link_to 'Show', profile
        %td= link_to 'Edit', edit_profile_path(profile)
        %td= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Profile', new_profile_path

app/views/profiles/new.html.haml
%h1 New profile

= render 'form'

= link_to 'Back', profiles_path

app/views/profiles/old_edit.html.haml
%h1 Editing profile

= render 'form'

= link_to 'Show', @profile
\|
= link_to 'Back', profiles_path

app/views/profiles/show.html.haml
%p
  %b Organization:
  = @profile.org
%p
  %b Second Organization:
  = @profile.org2
%p
  %b Main Machine:
  = @profile.machine_1
%p
  %b Alternate Machine:
  = @profile.machine_2
%p
  %b Grad:
  = @profile.grad

= link_to 'Edit', edit_profile_path(@profile), class: 'btn btn-light bg-dark text-light white'
= link_to 'Back to Dashboard', timetables_path, class: 'btn btn-light bg-dark text-light white'