config/routes.rb
Rails.application.routes.draw do
  resources :profiles

  match '/auth/:provider/callback', :to => 'sessions#create', :via => [:get, :post]
  match 'auth/failure', :to => 'sessions#failure', :via => [:get, :post]

  get 'sessions/clear'
  get 'session/debug'
  match 'sessions/destroy', :as => 'logout', :via => [:get, :post]
	resources :users, only: [:destroy] do
    resources :profiles, only: [:show, :edit, :update, :destroy]
  end

	resources :timetables do

	end
	get 'timesheets/landing', :as => :timesheets_landing
  root 'timesheets#landing'

  match 'timetables/admin', :as => 'timetables_admin', :via => [:get, :post]
  match 'timetables/admin/:id', :as => 'timetables_user', :to => 'timetables#user', :via => [:get, :post]
  match 'timetables/admin/:id/new', :as => 'user_new_timetable', :to => 'timetables#user_new', :via => [:get, :post]
  match 'timetables/admin/:id/:table_id', :as => 'timetables_user_edit', :to => 'timetables#user_edit', :via => [:get, :post]
  delete 'timetables/admin/:id/:table_id', :to => 'timetables#user_destroy'
  match 'timetables/admin_archive', :as => 'timetables_admin_archive', :via => [:get, :post]

end

app/controllers/timetables_controller.rb
require 'date'
require 'active_support/time'
require 'socket'
require 'csv'

class TimetablesController < ApplicationController
	before_action :set_timetable, only: [:show, :edit, :update, :destroy]
  Time.zone = 'Eastern Time (US & Canada)'
  def print
    flash[:notice] = "You successfully printed your timesheet. Please sign and deliver to your manager."
  end

  def setupOrgs
    @selectedOrgs = Array[@profile.org, @profile.org2]
		@selectedMachines = Array[@profile.machine_1, @profile.machine_2]
  end

  def index
    Time.zone = 'Eastern Time (US & Canada)'
    myid = current_user.id
    @profile = Profile.find_by(user_id: myid)
    @admin_user = admins.to_s.include? current_user.email.to_s
    manager_user
		Organization.all.each do |x|
			if x.num == @profile.org
				@orgnamefound1 = x.name
		  end
			if x.num == @profile.org2
				@orgnamefound2 = x.name
		  end
		end
    if params[:timetable] != nil
			sort_by_date
    else
			#show all of the users timetables
      @timetables = Timetable.get_user_timetables(myid).where('created_at >= ?', 4.week.ago)
    end
		convert_time
  end

  # GET /timetables/1
  def show
    Time.zone = 'Eastern Time (US & Canada)'
		id = params[:id] # retrieve movie ID from URI route
    @timetable = Timetable.find(id) # look up movie by unique ID
  end

  # GET /timetables/new
  def new
    Time.zone = 'Eastern Time (US & Canada)'
		#flag that indicates whether the user currently on a shift
		#prevents a user from spamming the clock in button
    @clocked_in = 1

	  @timetable= Timetable.create!(time_in: DateTime.now(), user_id: current_user.id)

	  #@clicked = true #true=>if clicked, disable button, false=>enable button
    #@timetable= Timetable.create!(:time_in=>DateTime.now())

    flash[:notice] = "You have successfully clocked in!"
		redirect_to timetables_path
  end

  # GET /timetables/1/edit
  def edit
    Time.zone = 'Eastern Time (US & Canada)'
    myid = current_user.id
    @profile = Profile.find_by(user_id: myid)
		@timetable = Timetable.find(params[:id])
    @admin_user = admins.to_s.include? current_user.email.to_s
		manager_user
		if @timetable.time_out == nil
			@timetable.update(time_out: DateTime.now())
      @clocked_in = 0
			#reset the clocked_in flag to 0
		end
    setupOrgs
	end

  def create
    Time.zone = 'Eastern Time (US & Canada)'
    @timetable = Timetable.new(timetable_params)
    if @timetable.save
      redirect_to @timetable, notice: 'Timetable was successfully created.'
    else
       render :new
		end
  end

  # PATCH/PUT /timetables/1
  def update
    Time.zone = 'Eastern Time (US & Canada)'
    if @timetable.update(timetable_params)
      redirect_to timetables_path,notice: 'Timetable was successfully updated.'
    end
  end

  # DELETE /timetables/1
  def destroy
    Time.zone = 'Eastern Time (US & Canada)'
    @timetable.destroy
		flash[:notice]= 'Timetable was successfully destroyed.'
    redirect_to timetables_url
  end

  # GET /timetables/admin
  def admin
    Time.zone = 'Eastern Time (US & Canada)'

    #Checks if current user is an admin
		@admin_user = admins.to_s.include? current_user.email.to_s

    # Gets list of archived users
    @archived_users = Array.new
    file = CSV.read('db/archived_users.csv', converters: :all)
    file.each do |row|
      @archived_users.push(row[0])
    end

    # Gets list of user profiles & users' names
    @profiles = (Profile.all.collect{|prof| prof})
		non_nil = Array.new
		is_nil = Array.new
		@profiles.each do |prof|
			if !(prof.user.nil?)
        non_nil.push(prof)
			else
				is_nil.push(prof)
			end
	  end
		non_nil = non_nil.sort_by { |prof| prof.user.name.split(' ').last }

    non_nil.each do |prof|
      names = prof.user.name.split(' ')
      firstname = names.first
      lastname = names.last
      prof.user.name = lastname + ' ' + firstname
    end

		@profiles = non_nil + is_nil
    @users = Array.new
    Profile.all.each do |x|
      if !(x.user.nil?)
        if !(@archived_users.include? x.user.id)
          @users.push(x.user.name)
        end
      end
    end

    # Gets list of organization names
    @allOrgs = Organization.all.collect{|org| org.name}

    manager_user
  end

  def manager_user
    if(!(params[:organization].nil?))
      i = 0;
      Organization.all.each do |x|
        if(!(params[:organization][i][:manager].blank?))
          x.update(manager: params[:organization][i][:manager])
        end
        i = i + 1
      end
    end
		@manager_orgs = Hash.new
		Organization.all.each do |x|
			@manager_orgs[x.num] = Organization.find_by(num: x.num).manager
		end
    @managers = Organization.all.collect{|org| org.manager}
    myid = current_user.id
    @manager_prof = Profile.find_by(user_id: myid)
    @manager_user = @managers.include? current_user.name
  end

  # GET /timetables/admin/1
  #Note: Exclusively used for admin viewing other timesheets
  def user
    Time.zone = 'Eastern Time (US & Canada)'
    id = params[:id]
    @id = id
    @profile = Profile.find_by(user_id: id)
    @name = @profile.user.name
		@email = @profile.user.email
		Organization.all.each do |x|
			if x.num == @profile.org
				@orgnamefound1 = x.name
			end
			if x.num == @profile.org2
				@orgnamefound2 = x.name
			end
		end
    if params[:timetable] != nil
			sort_by_date_user(id)
    else
			#show all of the users timetables
      @timetables = Timetable.get_user_timetables(id).where('created_at >= ?', 4.week.ago)
    end
		convert_time
  end

  # GET /timetables/admin/1/1
  #Note: Exclusively used for admin viewing other timesheets
  def user_edit
    Time.zone = 'Eastern Time (US & Canada)'
    @user_id = params[:id]
    @profile = Profile.find_by(user_id: @user_id)
    @timetable = Timetable.find(params[:table_id])
    @admin_user = admins.to_s.include? current_user.email.to_s
		manager_user
		if @timetable.time_out == nil
			@timetable.update(time_out: DateTime.now())
      @clocked_in = 0
			#reset the clocked_in flag to 0
		end
    setupOrgs
  end

  # GET /timetables/admin/1/new
	def user_new
		Time.zone = 'Eastern Time (US & Canada)'
		#flag that indicates whether the user currently on a shift
		#prevents a user from spamming the clock in button
		id = params[:id]
		@timetable = Timetable.create!(time_in: DateTime.now(), user_id: id)

		flash[:notice] = "You have successfully clocked in!"
		redirect_to timetables_user_path
	end

  # DELETE /timetables/admin/1
  def user_destroy
    Time.zone = 'Eastern Time (US & Canada)'
    @timetable = Timetable.find(params[:table_id])
    @timetable.destroy
		flash[:notice]= 'Timetable was successfully destroyed.'
    redirect_to timetables_user_url
  end

  # GET /timetables/admin/archive
  def admin_archive
    Time.zone = 'Eastern Time (US & Canada)'

    # Checks if current user is an admin
    @admin_user = admins.to_s.include? current_user.email.to_s

    # Gets list of users
    @users = Array.new
    Profile.all.each do |x|
      if !(x.user.nil?)
        @users.push([x.user.name, x.user.id])
      end
    end

    # Gets list of archived users
    @archived_users = Array.new
    file = CSV.read('db/archived_users.csv', converters: :all)
    file.each do |row|
      @archived_users.push(row[0])
    end

    # Gets list of archived user names
    @archived_users_names = Array.new
    @users.each do |x|
      if (@archived_users.include? x[1])
        @archived_users_names.push(x)
      end
    end

    # Adds user to archived users
    if(!(params[:archive_user].nil?) and !(@archived_users.include?(params[:archive_user].to_i)))
      archive_user = params[:archive_user]
      CSV.open("db/archived_users.csv", "a+") do |csv|
        csv << [archive_user]
      end
    end

    # Removes user from archived users
    if(!(params[:unarchive_user].nil?))
      @archived_users_names.each do |x|
        if(x.include?(params[:unarchive_user].to_i))
          unarchive_user = params[:unarchive_user].to_i
          file.delete_if do |row|
            row[0] == unarchive_user
          end
          CSV.open("db/archived_users.csv", "w") do |csv|
            csv << file
          end
        end
      end
    end

    manager_user
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timetable
      Time.zone = 'Eastern Time (US & Canada)'
      @timetable = Timetable.find(params[:id])
    end

		#Calculates the total hours and total shifts
	  def convert_time
      Time.zone = 'Eastern Time (US & Canada)'
      all_dates = Array.new
      @timetables.each do |x|
        time_in = x.time_in #Clock in
        all_dates.push(time_in.day)
      end
      @total_days = all_dates.uniq.length
			@total_hours = 0
			temp = 0
			@found_clocked = 0
      @weekly_hours = Array.new(@timetables.length(), 0)
      j = 0 #Current week
      for i in 0..@timetables.length()-1 do
				if @timetables[i].time_out == nil
					@found_clocked = 1
				end
				if @timetables[i].time_out != nil and @timetables[i].time_in != nil
					temp = (@timetables[i].time_out.to_time - @timetables[i].time_in.to_time)
          #Rounding to a quarter: (round(num * 4))/4
          @total_hours += (((temp / 3600)*4).round())/4.0
          @weekly_hours[j] += (((temp / 3600)*4).round())/4.0
          if i == @timetables.length()-1 || (@timetables[i].time_in.strftime("%W") != @timetables[i+1].time_in.strftime("%W"))
            j+=1
          end
				end
			end
			@total_hours = @total_hours.round(2)
		end

    # Only allow a trusted parameter "white list" through.
    def timetable_params
      Time.zone = 'Eastern Time (US & Canada)'
      params.require(:timetable).permit(:time_in, :time_out,:notes, :user_id, :clockout_org, :machine)
    end

		#parses through the form to filter the dates
	  def sort_by_date
      Time.zone = 'Eastern Time (US & Canada)'
		  myid = current_user.id
			fromyear = params[:timetable]["fromdate(1i)"]
      toyear = params[:timetable]["todate(1i)"]
      frommonth = params[:timetable]["fromdate(2i)"]

app/helpers/timetables_helper.rb
module TimetablesHelper
end

app/views/timetables/_form.html.haml
= form_for @timetable do |f|
  - if @timetable.errors.any?
    #error_explanation
      %h2= "#{pluralize(@timetable.errors.count, "error")} prohibited this timetable from being saved:"
      %ul
        - @timetable.errors.full_messages.each do |message|
          %li= message
  - if @admin_user or @manager_user
    .field
      = f.label :start
      = f.text_field :time_in

    .field
      = f.label :end
      = f.text_field :time_out

  .field
    = f.label "Organization:"
    = f.select(:clockout_org, @selectedOrgs, {prompt: 'Select an organization'})
  .field
    = f.label "Machine"
    = f.select(:machine, @selectedMachines, {prompt: 'Select a machine'})
  .field
    = f.label :notes
    = f.text_field :notes
  .actions
    .row_without_padding
      = f.submit 'Save', :class => 'btn bg-dark text-light white'
      = link_to 'Back to Dashboard', timetables_path, class: 'btn btn-light bg-dark text-light white'

app/views/timetables/admin.html.haml
= link_to 'Back to Dashboard', timetables_path, class: 'btn btn-light bg-dark text-light white'
%br
%br
= form_tag do
    - if !@manager_user or @admin_user
        %h1= "Organization Management"
        - for i in 0..@allOrgs.length()-1 do
            %div
                -if (@managers.any? && !(@managers[i].blank?)) #Checks for nil & empty strings
                    = label_tag "organization[][manager]", @allOrgs[i] + " - " + @managers[i]
                -else
                    = label_tag "organization[][manager]", @allOrgs[i] + " - N/A"
                = select_tag "organization[][manager]", options_for_select(@users), prompt: "Select a manager"
        = submit_tag 'Save', :class => 'btn bg-dark text-light white'
%br
    %h1= "User Timesheets"
    - for i in 0..@profiles.length()-1 do
        - if !(@profiles[i].user_id.nil?)
            -if !(@archived_users.include?(@profiles[i].user.id))
                - if @manager_user and !@admin_user
                    - if ( (@profiles[i].org == @manager_prof.org and @profiles[i].org != "" and @manager_prof.org != "" and @manager_orgs[@manager_prof.org] == @manager_prof.user.name) or (@profiles[i].org2 == @manager_prof.org and @profiles[i].org2 != "" and @manager_prof.org != "" and @manager_orgs[@manager_prof.org] == @manager_prof.user.name) or (@profiles[i].org == @manager_prof.org2 and @profiles[i].org != "" and @manager_prof.org2 != "" and @manager_orgs[@manager_prof.org2] == @manager_prof.user.name) or (@profiles[i].org2 == @manager_prof.org2 and @profiles[i].org2 != "" and @manager_prof.org2 != "" and @manager_orgs[@manager_prof.org2] == @manager_prof.user.name))
                        %li= link_to @profiles[i].user.name, timetables_user_path(@profiles[i].user.id.to_s)
                - else
                    %li= link_to @profiles[i].user.name, timetables_user_path(@profiles[i].user.id.to_s)

app/views/timetables/admin_archive.html.haml
= link_to 'Back to Dashboard', timetables_path, class: 'btn btn-light bg-dark text-light white'
%br
%br
= form_tag do
    - if !@manager_user or @admin_user
        %h3= "Archive User"
        = select_tag "archive_user",options_for_select(@users), prompt: "Select a user"
        %br
        %br
        = submit_tag 'Save', :class => 'btn bg-dark text-light white'
        %br
        %br
= form_tag do
    - if !@manager_user or @admin_user
        %h3= "Unarchive User"
        = select_tag "unarchive_user",options_for_select(@archived_users_names), prompt: "Select a user"
        %br  
        %br
        = submit_tag 'Save', :class => 'btn bg-dark text-light white'

app/views/timetables/edit.html.haml
%h1 Edit

= render 'form'

app/views/timetables/index.html.haml
%h1#name
  = "#{current_user.name}'s Timesheet"
%h2#email
  = "#{current_user.email}"
%br
%h4#orgs.some{:style => "line-height: 140%"}
  - if @profile.org != nil
    = "Group/Org#: #{@profile.org} #{@orgnamefound1}"
  - if @profile.org2 != nil
    %br
    = "Additional Group/Org#: #{@profile.org2} #{@orgnamefound2}"
  - if @profile.grad != nil
    %br
    - if @profile.grad == 0
      = "Graduate Student: No"
    - else
      = "Graduate Student: Yes"
.printer
  %br
    - if @found_clocked == 0
      = link_to 'Clock In', new_timetable_path, class: 'btn btn-light bg-primary text-light white'
    = link_to 'Profile Settings', edit_profile_path(@profile), class: 'btn btn-light bg-dark text-light white'
    = link_to "Guide", "https://docs.google.com/document/d/1okytR5K9YzO0yVjNTVR1zimIgcDAC6dEYu2vx6GkT-w/edit", target: :_blank, class: 'btn btn-light bg-success text-light white'
    = link_to "Payroll Calendar", "https://drive.google.com/file/d/1_hk3L6ffV81HXeXTFamKFVC6Sm7B1tmz/view", target: :_blank, class: 'btn btn-light bg-success text-light white'
  %br
  %br
  .printer
    %h6
      %mark
        Enter the proper pay period and click
        %b
          Refresh
        to print your timesheet.
    = form_tag timetables_path, method: :get, id: 'dates_form' do
      = label_tag :fromdate, "From: "

      - if @fromdate != nil
        = date_select "timetable", "fromdate", selected: @fromdate
      - else
        = date_select "timetable", "fromdate"

      = label_tag :todate, "To: "

      - if @todate != nil
        = date_select "timetable", "todate", selected: @todate
      - else
        = date_select "timetable", "todate"

      = submit_tag 'Refresh', id: 'dates_submit', class: 'btn btn-light bg-dark text-light white'

%br
%h5#begin
  = "Begin Date: #{@fromdateonly}"
%h5#end
  = "End Date: #{@todateonly}"
%h5#payroll
  = "Estimated Payday: #{@estimatedpayday}"
%br
.table-responsive
  %table#timetables.table.table-striped.col-md-12.some{:style => "text-align: center"}
    %thead
      %tr
        %th Day
        %th Time In
        %th Time Out
        %th Hours
        %th Department
        %th Machine
        %th Notes
        %th
        %th

    %tbody
      - week = 1
      - for i in 0..@timetables.length()-1 do
        %tr
          %td
            - if @timetables[i].time_in != nil
              = @timetables[i].time_in.strftime("%m/%d/%Y")
          %td
            - if @timetables[i].time_in != nil
              = @timetables[i].time_in.strftime("%l:%M %p")
          %td
            - if @timetables[i].time_out != nil
              = @timetables[i].time_out.strftime("%l:%M %p")
          %td
            - if @timetables[i].time_out != nil && @timetables[i].time_in != nil
              = (((((@timetables[i].time_out.to_time - @timetables[i].time_in.to_time) / 3600)*4).round())/4.0).round(2)
          %td
            = @timetables[i].clockout_org
          %td
            = @timetables[i].machine
          %td
            = @timetables[i].notes
          %td
            .printer
              - if @timetables[i].time_out != nil
                = link_to "Edit", edit_timetable_path(@timetables[i]), class: 'btn btn-primary text-light white'
          %td
            .printer
              - if @timetables[i].time_out != nil
                = link_to 'Delete', timetable_path(@timetables[i]), 'data-method' => 'delete', 'data-confirm' => 'Are you sure?', :class => 'btn btn-danger'
              - else
                = link_to 'Clock Out', edit_timetable_path(@timetables[i]),class: 'btn btn-light bg-dark text-light white'
        - if (@timetables[i].time_out != nil && @timetables[i].time_in != nil) && (i == @timetables.length()-1 || (@timetables[i].time_in.strftime("%W") != @timetables[i+1].time_in.strftime("%W")))
          %td
          %td
          %th Week #{week}
          %td
            = @weekly_hours[week-1]
          - week += 1
          %td
          %td
          %td
          %td
          %td
      %tr
        %th Total Days: #{@total_days}
        %th
        %th
        %th Total Hours: #{@total_hours}
        %th
        %th
        %th
        %th
        %th

.signatures
  %h4
    %br
    I certify to the best of my knowledge the hours listed above are correct.
.signatures
  %h4
    %br
    %br
    Employee Signature:____________________________  Date:___________________
    %br
    %br
    %br
    Manager Signature:_____________________________ Date:___________________
.printer
  = link_to 'Print Timesheet', '/timetables', :onclick => 'window.print();return false;',class: 'btn btn-light bg-dark text-light white', style: "float: right;"

app/views/timetables/new.html.haml
%h1 New timetable

= render 'form'

= link_to 'Back', timetables_path

app/views/timetables/show.html.haml
%p#notice= notice

%p
  %b Start:
  = @timetable.time_in
%p
  %b End:
  = @timetable.time_out
%p
  %b Notes:
  = @timetable.notes

.row
= link_to 'Back to Dashboard', timetables_path, class: 'btn btn-light bg-dark text-light white'

app/views/timetables/user.html.haml
.printer
  = link_to 'Back to Dashboard', timetables_path, class: 'btn btn-light bg-dark text-light white'
%br
%h1#name
  = "#{@name}'s Timesheet"
%h2#email
  = "#{@email}"
%br
%h4#orgs.some{:style => "line-height: 140%"}
  - if @profile.org != nil
    = "Group/Org#: #{@profile.org} #{@orgnamefound1}"
  - if @profile.org2 != nil
    %br
    = "Additional Group/Org#: #{@profile.org2} #{@orgnamefound2}"
  - if @profile.grad != nil
    %br
    - if @profile.grad == 0
      = "Graduate Student: No"
    - else
      = "Graduate Student: Yes"
.printer
  %br
    - if @found_clocked == 0
      = link_to 'Clock In', user_new_timetable_path, class: 'btn btn-light bg-primary text-light white'
    = link_to 'Profile Settings', edit_profile_path(@profile), class: 'btn btn-light bg-dark text-light white'
    = link_to "Guide", "https://docs.google.com/document/d/1okytR5K9YzO0yVjNTVR1zimIgcDAC6dEYu2vx6GkT-w/edit", target: :_blank, class: 'btn btn-light bg-success text-light white'
    = link_to "Payroll Calendar", "https://drive.google.com/file/d/1_hk3L6ffV81HXeXTFamKFVC6Sm7B1tmz/view", target: :_blank, class: 'btn btn-light bg-success text-light white'
    %br
  .printer
    %br
    = form_tag timetables_user_path, method: :get, id: 'dates_form' do
      = label_tag :fromdate, "From: "

      - if @fromdate != nil
        = date_select "timetable", "fromdate", selected: @fromdate
      - else
        = date_select "timetable", "fromdate"

      = label_tag :todate, "To: "

      - if @todate != nil
        = date_select "timetable", "todate", selected: @todate
      - else
        = date_select "timetable", "todate"

      = submit_tag 'Refresh', id: 'dates_submit', class: 'btn btn-light bg-dark text-light white'
%br
%h5#begin
  = "Begin Date: #{@fromdateonly}"
%h5#end
  = "End Date: #{@todateonly}"
%h5#payroll
  = "Estimated Payday: #{@estimatedpayday}"
%br
.table-responsive
  %table#timetables.table.table-striped.col-md-12.some{:style => "text-align: center"}
    %thead
      %tr
        %th Day
        %th Time In
        %th Time Out
        %th Hours
        %th Department
        %th Machine
        %th Notes
        %th
        %th

    %tbody
      - week = 1
      - for i in 0..@timetables.length()-1 do
        %tr
          %td
            - if @timetables[i].time_in != nil
              = @timetables[i].time_in.strftime("%m/%d/%Y")
          %td
            - if @timetables[i].time_in != nil
              = @timetables[i].time_in.strftime("%l:%M %p")
          %td
            - if @timetables[i].time_out != nil
              = @timetables[i].time_out.strftime("%l:%M %p")
          %td
            - if @timetables[i].time_out != nil && @timetables[i].time_in != nil
              = (((((@timetables[i].time_out.to_time - @timetables[i].time_in.to_time) / 3600)*4).round())/4.0).round(2)
          %td
            = @timetables[i].clockout_org
          %td
            = @timetables[i].machine
          %td
            = @timetables[i].notes
          %td
            .printer
              - if @timetables[i].time_out != nil
                = link_to "Edit", timetables_user_edit_path(@id, @timetables[i]), class: 'btn btn-primary text-light white'
          %td
            .printer
              - if @timetables[i].time_out != nil
                = link_to 'Delete', timetables_user_edit_path(@id.to_s, @timetables[i]), 'data-method' => 'delete', 'data-confirm' => 'Are you sure?', :class => 'btn btn-danger'
              - else
                = link_to 'Clock Out', timetables_user_edit_path(@id, @timetables[i]),class: 'btn btn-light bg-dark text-light white'
        - if i == @timetables.length()-1 || (@timetables[i].time_in.strftime("%W") != @timetables[i+1].time_in.strftime("%W"))
          %td
          %td
          %th Week #{week}
          %td
            = @weekly_hours[week-1]
          - week += 1
          %td
          %td
          %td
          %td
          %td
      %tr
        %th Total Days: #{@total_days}
        %th
        %th
        %th Total Hours: #{@total_hours}
        %th
        %th
        %th
        %th
        %th

.signatures
  %h4
    %br
    I certify to the best of my knowledge the hours listed above are correct.
.signatures
  %h4
    %br
    %br
    Employee Signature:____________________________  Date:___________________
    %br
    %br
    %br
    Manager Signature:_____________________________ Date:___________________
.printer
  = link_to 'Print Timesheet', '/timetables', :onclick => 'window.print();return false;',class: 'btn btn-light bg-dark text-light white', style: "float: right;"

app/views/timetables/user_edit.html.haml
%h1 Edit


= render 'form'