config/routes.rb
Rails.application.routes.draw do
  resources :profiles

  match '/auth/:provider/callback', :to => 'sessions#create', :via => [:get, :post]
  match 'auth/failure', :to => 'sessions#failure', :via => [:get, :post]

  get 'sessions/clear'
  get 'session/debug'
  match 'sessions/destroy', :as => 'logout', :via => [:get, :post]
	resources :users, only: [:destroy] do
    resources :profiles, only: [:show, :edit, :update, :destroy]
  end

	resources :timetables do

	end
	get 'timesheets/landing', :as => :timesheets_landing
  root 'timesheets#landing'

  match 'timetables/admin', :as => 'timetables_admin', :via => [:get, :post]
  match 'timetables/admin/:id', :as => 'timetables_user', :to => 'timetables#user', :via => [:get, :post]
  match 'timetables/admin/:id/new', :as => 'user_new_timetable', :to => 'timetables#user_new', :via => [:get, :post]
  match 'timetables/admin/:id/:table_id', :as => 'timetables_user_edit', :to => 'timetables#user_edit', :via => [:get, :post]
  delete 'timetables/admin/:id/:table_id', :to => 'timetables#user_destroy'
  match 'timetables/admin_archive', :as => 'timetables_admin_archive', :via => [:get, :post]

end

app/views/layouts/_flash.haml
- if flash[:notice]
  #notice.alert.alert-info{role: "alert"}
    = flash[:notice]
- elsif flash[:warning]
  #warning.alert.alert-danger{role: "alert"}
    = flash[:warning]

app/views/layouts/_footer.html.haml
%div
= button_to "Log Out", logout_path, class: 'btn btn-light bg-dark text-light white row_with_padding'

app/views/layouts/application.html.haml
!!!
%html
  %body
    %title SA Timesheet
    %link{crossorigin: "anonymous", href: "https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css", integrity: "sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z", rel: "stylesheet"}/
    = stylesheet_link_tag 'application', 'media' => 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    %nav.navbar.navbar-expand-lg.bg-success.text-white.mb-3
      = image_tag "SAlogo.png"
      .banner_text
        - unless @action == 'login'
          - if (@admin_user || @manager_user)
            = button_to " Archive Users", timetables_admin_archive_path, class: "btn btn-light bg-dark text-light white"
            = button_to " View Users", timetables_admin_path, class: "btn btn-light bg-dark text-light white"
          = button_to " Log Out", logout_path, class: "btn btn-light bg-dark text-light white"
    .container
      .flash
        = render 'layouts/flash'
      %main#main
        = yield
      
        